In [ ]:
import pandas as pd
import numpy as np

In [ ]:
var1=np.random.randn(100)


In [ ]:
import pandas as pd
import numpy as np


In [ ]:

#generate random data form a normal
var1=np.random.randn(100)
var1
#generate a second set of data
var2=np.random.rand(100)-0.1>0
var2
#generate a label
labels=["Profit" " Returns"]



In [ ]:
#create a dictionary
Dddd={"labels[0]":var1, "labels[1]":var2}

In [ ]:
print(D)

In [ ]:
ret=D.get("labels[0]")
ret

In [ ]:
#turn the dictionary into a data frame
df=pd.DataFrame(data=Dddd)
type(df)

pandas.core.frame.DataFrame

In [ ]:
df


In [ ]:
df.mean()


labels[0]   -0.16902
labels[1]    0.87000
dtype: float64

In [ ]:
dfnew = pd.DataFrame({'a':[1, 2, 3, 4, 5],
                     'b': [6, 7, 8, 9, 10],
                     'c': [11,12, 13, 14, 15],
                     'd': [16,17,19,19,20]},
           index=[1,2,3,4,5])
#with this syntax I am specifying columns

In [ ]:
dfnew
type(dfnew)



pandas.core.frame.DataFrame

In [ ]:
cat=pd.DataFrame(
    [[1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11,12, 13, 14, 15],
    [16,17,19,19,20]],
    index=[1,2,3,4],
    columns=["a","b","c","d","e"])
#with this syntax i specify rows

In [ ]:
cat

a   b   c   d   e
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  19  19  20

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.mean()
# exercise compute the mean by row

In [ ]:
dfnnewbad= pd.DataFrame({'x': [1, 2, 3, 4, 5],
                   'y': [6, 7, 8, 9, 10],
                   'z': [11,12, 13, 14, 15],
                   'w': [16,17,19,19,20]})


In [ ]:
dfnnewbad

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.iloc[1]
#here I am selecting the second row of the dataframe called dfnew
type(dfnew.iloc[1])
#you can see that the result is still a dataframe
dfnew.iloc[0]

In [ ]:
dfnew.iloc[:,2]
#here I am selecting all rows so : , and the third column

1    11
2    12
3    13
4    14
5    15
Name: c, dtype: int64

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.iloc[:, 0:2]
#here I am selecting all rows and  colums zero to two, but the column two ( which for us is called colum c) is excluded

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.iloc[0:3,:]

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.iloc[1:2]

In [ ]:
dfnew.iloc[:,1]

1     6
2     7
3     8
4     9
5    10
Name: b, dtype: int64

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.iloc[:,1::]
#this is a different syntax, which is preserving the names of the column

In [ ]:
dfnew.iloc[:,1:2]
dfnew.iloc[1:2]

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
dfnew.head(2)
#show the first 2 rows

In [ ]:
dfnew.tail(2)
#shows the last 2 rows


a   b   c   d
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
pd.melt(dfnew)
#melt columninto rows


In [ ]:

newframe=pd.concat([dfnew,cat])
newframe
#here concatenation is by rows , if dimensions are not compatible

a   b   c   d     e
1   1   6  11  16   NaN
2   2   7  12  17   NaN
3   3   8  13  19   NaN
4   4   9  14  19   NaN
5   5  10  15  20   NaN
1   1   2   3   4   5.0
2   6   7   8   9  10.0
3  11  12  13  14  15.0
4  16  17  19  19  20.0

In [ ]:
pd.concat([dfnew,cat], axis=1)
#here concatenation is by columns

In [ ]:
dfnew.sample(n=3)
#randomly selects 3 rows

a   b   c   d
1  1   6  11  16
5  5  10  15  20
4  4   9  14  19

In [ ]:
dfnew.nlargest(2, "a")

a   b   c   d
5  5  10  15  20
4  4   9  14  19

In [ ]:
dfnew

a   b   c   d
1  1   6  11  16
2  2   7  12  17
3  3   8  13  19
4  4   9  14  19
5  5  10  15  20

In [ ]:
#example of selection with logical operators
startpoint="b"
endpoint="c"
dflast= dfnew.loc[:,(dfnew.columns>=startpoint)&(dfnew.columns<=endpoint)]

In [ ]:
dflast

b   c
1   6  11
2   7  12
3   8  13
4   9  14
5  10  15

In [ ]:
#now I am going to import some data which I saved on my one drive so first I connect my Coolab to my one drive
from google.colab import drive
drive.mount('/content/drive')


In [ ]:
dfexample= pd.read_excel("/content/drive/MyDrive/datamalvina/week1.xlsx")


In [ ]:

dfexample.head(5)

Unnamed: 0     GDP     PCE    Inv       G
0 1980-03-01  5903.4  3796.7  778.3  1365.4
1 1980-06-01  5782.4  3710.5  708.1  1369.7
2 1980-09-01  5771.7  3750.3  654.1  1350.8
3 1980-12-01  5878.4  3800.3  720.6  1349.4
4 1981-03-01  6000.6  3821.1  792.2  1367.3

In [ ]:
dfexample2= dfexample.rename(columns={"Unnamed: 0" : 'Date'})
#here it is space sensitive
dfexample2

Date      GDP     PCE     Inv       G
0   1980-03-01   5903.4  3796.7   778.3  1365.4
1   1980-06-01   5782.4  3710.5   708.1  1369.7
2   1980-09-01   5771.7  3750.3   654.1  1350.8
3   1980-12-01   5878.4  3800.3   720.6  1349.4
4   1981-03-01   6000.6  3821.1   792.2  1367.3
..         ...      ...     ...     ...     ...
124 2011-03-01  13227.9  9376.7  1750.9  2513.9
125 2011-06-01  13271.8  9392.7  1778.4  2508.2
126 2011-09-01  13331.6  9433.5  1784.2  2507.6
127 2011-12-01  13429.0  9482.1  1875.7  2481.2
128 2012-03-01  13502.4  9550.2  1903.0  2462.2

[129 rows x 5 columns]

In [ ]:
dfexample2

Date      GDP     PCE     Inv       G
0   1980-03-01   5903.4  3796.7   778.3  1365.4
1   1980-06-01   5782.4  3710.5   708.1  1369.7
2   1980-09-01   5771.7  3750.3   654.1  1350.8
3   1980-12-01   5878.4  3800.3   720.6  1349.4
4   1981-03-01   6000.6  3821.1   792.2  1367.3
..         ...      ...     ...     ...     ...
124 2011-03-01  13227.9  9376.7  1750.9  2513.9
125 2011-06-01  13271.8  9392.7  1778.4  2508.2
126 2011-09-01  13331.6  9433.5  1784.2  2507.6
127 2011-12-01  13429.0  9482.1  1875.7  2481.2
128 2012-03-01  13502.4  9550.2  1903.0  2462.2

[129 rows x 5 columns]

In [ ]:
dfexample2.columns

Index(['Date', 'GDP', 'PCE', 'Inv', 'G'], dtype='object')

In [ ]:
data = {
    'integer':np.arange(0,2,1),
    'Square':np.arange(2)**2,
    'Log':np.log(np.arange(0,2,1))
}


df=pd.DataFrame(data)

df
type(data)

<ipython-input-78-c7d91aa545ce>:4: RuntimeWarning: divide by zero encountered in log
  'Log':np.log(np.arange(0,2,1))


dict

In [ ]:
dfshinhao = pd.DataFrame(
    [[0, 0, np.log(0)],
     [1, 1^2, np.log(1)],
     [2, 2^2, np.log(2)]],
    index=[1, 2, 3],
    columns=['integer', 'square', 'log'])

dfshinhao

In [ ]:
data

{'integer': array([0, 1]), 'Square': array([0, 1]), 'Log': array([-inf,   0.])}

In [ ]:
# Time for exercise n2 week 2
#I want to extract some columns only over some dates, for example
#I want to work with data only on G and Inv and I want to restrict the samplebetween Jan 2009 and Dec 2011



In [ ]:
import pandas as ps
import numpy as np


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
x=np.array([4,9,10]) # one dimensional array
y=np.array(["Hannah","Malvina","George"])
type(x)

numpy.ndarray

In [ ]:
c=np.array([[1.5,3,8], [3,2,1]]) # notice that [] generates a new row of the array
c

array([[1.5, 3. , 8. ],
       [3. , 2. , 1. ]])

In [ ]:
cc=np.array([[(1,2,3),(4,5,6)],[(7,8,9), (9,3,1)]],dtype=float)
cc

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [9., 3., 1.]]])

In [ ]:
d=np.random.chisquare(5)
d
e=np.random.random(5)
e

array([0.95163475, 0.88700175, 0.53657878, 0.18162532, 0.60702612])

In [ ]:
d=np.random.chisquare(5)
d

2.7686823875168263

In [ ]:
#generate 12 random numbers from a t distribution with 3 degrees of freedom

In [ ]:
f=np.random.random((2,3))
f

array([[0.83322344, 0.12585525, 0.16803719],
       [0.17713728, 0.04506711, 0.35315073]])

In [ ]:
#generate a 3 dim array with 6 elements in each array , where all elements are from a chi-squared with 4 degrees of freedoms

In [ ]:
k=np.zeros((4,7))
k

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
j=np.empty((1,3))
j

array([[2.0e-323, 4.4e-323, 4.9e-323]])

In [ ]:
c

array([[1.5, 3. , 8. ],
       [3. , 2. , 1. ]])

In [ ]:
c.shape

(2, 3)

In [ ]:
len(c)

2

In [ ]:
c.size

6

In [ ]:
c.dtype

dtype('float64')

In [ ]:
np.info(np.random)

In [ ]:
c

array([[1.5, 3. , 8. ],
       [3. , 2. , 1. ]])

In [ ]:
cc

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [9., 3., 1.]]])

In [ ]:
l=c+cc
l

array([[[ 2.5,  5. , 11. ],
        [ 7. ,  7. ,  7. ]],

       [[ 8.5, 11. , 17. ],
        [12. ,  5. ,  2. ]]])

In [ ]:
# sun a two dimensional array with  a 3 dimensional array and check : 1- if you can , 2- what is the logic of the sum

In [ ]:
np.log(c)

array([[0.40546511, 1.09861229, 2.07944154],
       [1.09861229, 0.69314718, 0.        ]])

In [ ]:
c

array([[1.5, 3. , 8. ],
       [3. , 2. , 1. ]])

In [ ]:
f

array([[0.83322344, 0.12585525, 0.16803719],
       [0.17713728, 0.04506711, 0.35315073]])

In [ ]:
f==c

array([[False, False, False],
       [False, False, False]])

In [ ]:
c>9

array([[False, False, False],
       [False, False, False]])

In [ ]:
c<3

array([[ True, False, False],
       [False,  True,  True]])

In [ ]:
c

array([[1.5, 3. , 8. ],
       [3. , 2. , 1. ]])

In [ ]:
e

array([0.95163475, 0.88700175, 0.53657878, 0.18162532, 0.60702612])

In [ ]:
np.info(np.corrcoef)

In [ ]:
e.corrcoef(0.5)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np

In [4]:
b=np.array ([[1.5, 3. , 8. ],
       [3. , 2. , 1. ]])

In [10]:
cat= b.sum()
print(cat)

18.5


In [11]:
dog= b.min()
print(dog)

1.0


In [14]:
f= b.sort()
print(f)

None


In [17]:
a= np.array([[12.,7.,3.], [13.,9.,4.]])

In [16]:
i=np.transpose(b)
print(i)

[[1.5 1. ]
 [3.  2. ]
 [8.  3. ]]


In [ ]:
#  Exercise 3 week 5 :consider the data of exercise 2 , compute the correlation coeff for G and Inv respectely

In [20]:
print(a)
print(b)

[[12.  7.  3.]
 [13.  9.  4.]]
[[1.5 3.  8. ]
 [1.  2.  3. ]]


In [24]:
c=np.concatenate((a,b), axis=0)
print(c)

[[12.   7.   3. ]
 [13.   9.   4. ]
 [ 1.5  3.   8. ]
 [ 1.   2.   3. ]]


In [ ]:
d=np.vstack((a,b))
print(d)

In [26]:
e=np.r_[a,b]
print(e)

[[12.   7.   3. ]
 [13.   9.   4. ]
 [ 1.5  3.   8. ]
 [ 1.   2.   3. ]]


In [27]:
g=np.column_stack((a,b))
print(g)

[[12.   7.   3.   1.5  3.   8. ]
 [13.   9.   4.   1.   2.   3. ]]
